load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
  name = "string-utils",
  hdrs = ["string-utils.h"],
  srcs = ["string-utils.cc"],
  visibility = ["//cc:__subpackages__"],
  deps = [
      "@com_google_absl//absl/strings",
  ],
)
